const mongoose = require('mongoose');

const taskSchema = new mongoose.Schema(
  {
    userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    subjectId: { type: mongoose.Schema.Types.ObjectId, ref: 'Subject', default: null },
    topic: { type: String, required: true },
    description: { type: String, default: '' },
    scheduledTime: { type: Date, default: null, index: true },
    duration: { type: Number, default: 60 }, // in minutes
    completed: { type: Boolean, default: false },
    status: { type: String, enum: ['pending', 'completed', 'skipped'], default: 'pending' },
    priority: { type: Number, min: 1, max: 5, default: 2 },
    deadline: { type: Date, default: null, index: true },
    isAutoGenerated: { type: Boolean, default: false },
  },
  { timestamps: true }
);

module.exports = mongoose.model('Task', taskSchema);
