const mongoose = require('mongoose');
require('dotenv').config();

// Connect to database
mongoose.connect(process.env.MONGODB_URI)
  .then(() => console.log('MongoDB connected'))
  .catch(err => console.error('MongoDB connection error:', err));

// Define Task model (same as in your app)
const TaskSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
  subjectId: { type: mongoose.Schema.Types.ObjectId, ref: 'Subject', default: null },
  topic: { type: String, required: true },
  description: { type: String, default: '' },
  scheduledTime: { type: Date, default: null, index: true },
  duration: { type: Number, default: 60 },
  completed: { type: Boolean, default: false },
  status: { type: String, enum: ['pending', 'completed', 'skipped'], default: 'pending' },
  priority: { type: Number, min: 1, max: 5, default: 2 },
  deadline: { type: Date, default: null, index: true },
  isAutoGenerated: { type: Boolean, default: false },
}, { timestamps: true });

const Task = mongoose.model('Task', TaskSchema);

async function debugTasks() {
  try {
    console.log('🔍 Debugging Task collection...');
    
    // Count all tasks
    const totalTasks = await Task.countDocuments();
    console.log('Total tasks in database:', totalTasks);
    
    // Find all tasks
    const allTasks = await Task.find({});
    console.log('All tasks:');
    allTasks.forEach((task, index) => {
      console.log(`${index + 1}. ${task.topic} (User: ${task.userId}, Status: ${task.status})`);
    });
    
    // Find tasks for specific user
    const userId = '69c2a6a14a7a54cbd18365d1';
    const userTasks = await Task.find({ userId });
    console.log(`\nTasks for user ${userId}:`, userTasks.length);
    userTasks.forEach((task, index) => {
      console.log(`${index + 1}. ${task.topic} (Status: ${task.status})`);
    });
    
    // Test populate
    console.log('\nTesting populate...');
    const populatedTasks = await Task.find({ userId })
      .populate('subjectId', 'name priority');
    console.log('Populated tasks:', populatedTasks.length);
    
  } catch (error) {
    console.error('Error:', error);
  } finally {
    mongoose.connection.close();
  }
}

debugTasks();
