const Subject = require('../models/Subject');
const Task = require('../models/Task');
const User = require('../models/User');

/**
 * Scoring logic:
 *   score = subjectPriority * 2  +  topicDifficulty  +  recencyBonus
 *
 * recencyBonus: if topic was never studied → +5
 *              if studied > 7 days ago    → +3
 *              if studied > 3 days ago    → +1
 *              else                       →  0
 *
 * Time allocation: user's dailyStudyHours is distributed proportionally
 * to each selected topic's score × estimatedTime.
 * A topic session is capped at its estimatedTime (minutes).
 */
function scoreTopics(subjects) {
  const now = Date.now();
  const DAY_MS = 86_400_000;
  const scored = [];

  for (const subject of subjects) {
    for (const topic of subject.topics) {
      if (topic.completed) continue; // skip already completed

      let recencyBonus = 5; // never studied
      if (topic.lastStudied) {
        const daysSince = (now - new Date(topic.lastStudied).getTime()) / DAY_MS;
        if (daysSince <= 3) recencyBonus = 0;
        else if (daysSince <= 7) recencyBonus = 1;
        else recencyBonus = 3;
      }

      const score =
        subject.priority * 2 + topic.difficulty + recencyBonus;

      scored.push({
        subjectId: subject._id,
        subjectName: subject.name,
        topicId: topic._id,
        topicTitle: topic.title,
        difficulty: topic.difficulty,
        estimatedTime: topic.estimatedTime || 60, // minutes
        score,
      });
    }
  }

  // Sort descending by score
  scored.sort((a, b) => b.score - a.score);
  return scored;
}

function allocateTime(scoredTopics, totalMinutes) {
  if (!scoredTopics.length || totalMinutes <= 0) return [];

  const plan = [];
  let remaining = totalMinutes;

  for (const item of scoredTopics) {
    if (remaining <= 0) break;

    const allotted = Math.min(item.estimatedTime, remaining);
    if (allotted < 10) break; // don't schedule < 10-min sessions

    plan.push({
      subjectId: item.subjectId,
      subjectName: item.subjectName,
      topicId: item.topicId,
      topicTitle: item.topicTitle,
      difficulty: item.difficulty,
      allocatedMinutes: allotted,
      score: item.score,
    });

    remaining -= allotted;
  }

  return plan;
}

function buildTimeSlots(plan, preferredSlots, targetDate) {
  // Slot start times (hour in 24h)
  const slotMap = {
    morning: 8,
    afternoon: 13,
    evening: 18,
    night: 21,
  };

  const base = new Date(targetDate);
  base.setHours(0, 0, 0, 0);

  // Pick first valid slot or default 8 AM
  const slotKey = preferredSlots?.[0] || 'morning';
  let currentHour = slotMap[slotKey] ?? 8;
  let currentMin = 0;

  return plan.map((item, idx) => {
    const scheduledTime = new Date(base);
    scheduledTime.setHours(currentHour, currentMin, 0, 0);

    // Advance for next task
    currentMin += item.allocatedMinutes + 10; // 10-min break
    if (currentMin >= 60) {
      currentHour += Math.floor(currentMin / 60);
      currentMin = currentMin % 60;
    }

    return {
      ...item,
      scheduledTime,
    };
  });
}

// @desc  Generate daily study plan (dry run — returns plan without saving)
// @route GET /api/study-plan?date=YYYY-MM-DD
const getStudyPlan = async (req, res) => {
  try {
    const targetDate = req.query.date ? new Date(req.query.date) : new Date();
    const user = await User.findById(req.user._id);
    const subjects = await Subject.find({ userId: req.user._id });

    const totalMinutes = (user.preferences?.dailyStudyHours || 4) * 60;
    const preferredSlots = user.preferences?.preferredTimeSlots || ['morning'];

    const scoredTopics = scoreTopics(subjects);
    const timePlan = allocateTime(scoredTopics, totalMinutes);
    const plan = buildTimeSlots(timePlan, preferredSlots, targetDate);

    res.json({
      date: targetDate.toISOString().split('T')[0],
      totalMinutes,
      topicsScheduled: plan.length,
      plan,
    });
  } catch (error) {
    console.error('getStudyPlan error:', error);
    res.status(500).json({ message: 'Server error generating study plan' });
  }
};

// @desc  Generate and SAVE daily study plan as Tasks
// @route POST /api/study-plan/generate
const generateAndSavePlan = async (req, res) => {
  try {
    console.log(req.body);
    const { date, overwrite } = req.body;
    const targetDate = date ? new Date(date) : new Date();
    const dayStart = new Date(targetDate);
    dayStart.setHours(0, 0, 0, 0);
    const dayEnd = new Date(dayStart);
    dayEnd.setDate(dayEnd.getDate() + 1);

    // Optionally remove existing auto-generated tasks for this day
    if (overwrite) {
      await Task.deleteMany({
        userId: req.user._id,
        isAutoGenerated: true,
        scheduledTime: { $gte: dayStart, $lt: dayEnd },
      });
    }

    const user = await User.findById(req.user._id);
    const subjects = await Subject.find({ userId: req.user._id });
    const totalMinutes = (user.preferences?.dailyStudyHours || 4) * 60;
    const preferredSlots = user.preferences?.preferredTimeSlots || ['morning'];

    const scoredTopics = scoreTopics(subjects);
    const timePlan = allocateTime(scoredTopics, totalMinutes);
    const plan = buildTimeSlots(timePlan, preferredSlots, targetDate);

    if (!plan.length) {
      return res.json({ message: 'No incomplete topics found to schedule', tasks: [] });
    }

    const taskDocs = plan.map((item) => ({
      userId: req.user._id,
      subjectId: item.subjectId,
      topic: item.topicTitle,
      scheduledTime: item.scheduledTime,
      duration: item.allocatedMinutes,
      completed: false,
      isAutoGenerated: true,
    }));

    const tasks = await Task.insertMany(taskDocs);
    res.status(201).json({
      date: targetDate.toISOString().split('T')[0],
      tasksCreated: tasks.length,
      tasks,
    });
  } catch (error) {
    console.error('generateAndSavePlan error:', error);
    res.status(500).json({ message: 'Server error saving study plan' });
  }
};

module.exports = { getStudyPlan, generateAndSavePlan };
