const Task = require('../models/Task');
const Subject = require('../models/Subject');

// @desc  Get all tasks for logged-in user
// @route GET /api/tasks
const getTasks = async (req, res) => {
  try {
    const filter = { userId: req.user._id };

    // Optional query filters
    if (req.query.completed !== undefined) {
      filter.completed = req.query.completed === 'true';
    }
    if (req.query.date) {
      const day = new Date(req.query.date);
      const nextDay = new Date(day);
      nextDay.setDate(nextDay.getDate() + 1);
      filter.scheduledTime = { $gte: day, $lt: nextDay };
    }

    const tasks = await Task.find(filter)
      .sort({ scheduledTime: 1 })
      .populate('subjectId', 'name priority');

    res.json(tasks);
  } catch (error) {
    console.error('getTasks error:', error);
    res.status(500).json({ message: 'Server error fetching tasks' });
  }
};

// @desc  Get single task
// @route GET /api/tasks/:id
const getTask = async (req, res) => {
  try {
    const task = await Task.findOne({ _id: req.params.id, userId: req.user._id }).populate('subjectId', 'name priority');
    if (!task) return res.status(404).json({ message: 'Task not found' });
    res.json(task);
  } catch (error) {
    console.error('getTask error:', error);
    res.status(500).json({ message: 'Server error fetching task' });
  }
};

// @desc  Create a manual task
// @route POST /api/tasks
const createTask = async (req, res) => {
  try {
    const { topic, subjectId, scheduledTime, duration, deadline } = req.body;
    if (!topic) return res.status(400).json({ message: 'Topic is required' });

    const task = await Task.create({
      userId: req.user._id,
      topic,
      subjectId: subjectId || null,
      scheduledTime: scheduledTime || null,
      duration: duration || 60,
      deadline: deadline || null,
      isAutoGenerated: false,
    });

    res.status(201).json(task);
  } catch (error) {
    console.error('createTask error:', error);
    res.status(500).json({ message: 'Server error creating task' });
  }
};

// @desc  Update a task
// @route PUT /api/tasks/:id
const updateTask = async (req, res) => {
  try {
    const { topic, subjectId, scheduledTime, duration, completed, deadline } = req.body;
    const task = await Task.findOneAndUpdate(
      { _id: req.params.id, userId: req.user._id },
      { $set: { topic, subjectId, scheduledTime, duration, completed, deadline } },
      { new: true, runValidators: true }
    );
    if (!task) return res.status(404).json({ message: 'Task not found' });
    res.json(task);
  } catch (error) {
    console.error('updateTask error:', error);
    res.status(500).json({ message: 'Server error updating task' });
  }
};

// @desc  Delete a task
// @route DELETE /api/tasks/:id
const deleteTask = async (req, res) => {
  try {
    const task = await Task.findOneAndDelete({ _id: req.params.id, userId: req.user._id });
    if (!task) return res.status(404).json({ message: 'Task not found' });
    res.json({ message: 'Task deleted' });
  } catch (error) {
    console.error('deleteTask error:', error);
    res.status(500).json({ message: 'Server error deleting task' });
  }
};

// @desc  Mark task as complete / incomplete
// @route PATCH /api/tasks/:id/complete
const completeTask = async (req, res) => {
  try {
    const task = await Task.findOne({ _id: req.params.id, userId: req.user._id });
    if (!task) return res.status(404).json({ message: 'Task not found' });

    task.completed = !task.completed;
    await task.save();
    res.json(task);
  } catch (error) {
    console.error('completeTask error:', error);
    res.status(500).json({ message: 'Server error toggling task completion' });
  }
};

module.exports = { getTasks, getTask, createTask, updateTask, deleteTask, completeTask };
