const Task = require('../models/Task');
const Subject = require('../models/Subject');

// @desc  Get all tasks for logged-in user
// @route GET /api/tasks
const getTasks = async (req, res) => {
  try {
    if (!req.user || !req.user._id) {
      return res.status(401).json({ message: 'User authentication required' });
    }
    
    const filter = { userId: req.user._id };

    // Optional query filters
    if (req.query.completed !== undefined) {
      filter.completed = req.query.completed === 'true';
    }
    if (req.query.date) {
      const day = new Date(req.query.date);
      const nextDay = new Date(day);
      nextDay.setDate(nextDay.getDate() + 1);
      filter.scheduledTime = { $gte: day, $lt: nextDay };
    }

    const tasks = await Task.find(filter)
      .sort({ scheduledTime: 1 });

    res.json(tasks);
  } catch (error) {
    res.status(500).json({ message: 'Server error fetching tasks' });
  }
};

// @desc  Get single task
// @route GET /api/tasks/:id
const getTask = async (req, res) => {
  try {
    // Validate ObjectId format
    if (!req.params.id.match(/^[0-9a-fA-F]{24}$/)) {
      return res.status(400).json({ message: 'Invalid task ID format' });
    }
    
    const task = await Task.findOne({ _id: req.params.id, userId: req.user._id }).populate('subjectId', 'name priority');
    if (!task) return res.status(404).json({ message: 'Task not found' });
    res.json(task);
  } catch (error) {
    res.status(500).json({ message: 'Server error fetching task' });
  }
};

// @desc  Create a manual task
// @route POST /api/tasks
const createTask = async (req, res) => {
  try {
    const { topic, title, description, subjectId, scheduledTime, duration, deadline, dueDate, priority, status } = req.body;
    
    // Handle both frontend (title) and backend (topic) field names
    const taskTopic = topic || title;
    // Handle both frontend (dueDate) and backend (deadline) field names
    const taskDeadline = deadline || dueDate;
    
    if (!taskTopic) return res.status(400).json({ message: 'Topic/Title is required' });

    // Verify subject ownership if subjectId is provided
    if (subjectId) {
      const subject = await Subject.findOne({ _id: subjectId, userId: req.user._id });
      if (!subject) {
        return res.status(403).json({ message: 'Access denied: Subject not found or does not belong to user' });
      }
    }

    const task = await Task.create({
      userId: req.user._id,
      topic: taskTopic,
      description: description || '',
      subjectId: subjectId || null,
      scheduledTime: scheduledTime || null,
      duration: duration || 60,
      deadline: taskDeadline || null,
      priority: priority || 2,
      status: status || 'pending',
      isAutoGenerated: false,
    });

    res.status(201).json(task);
  } catch (error) {
    res.status(500).json({ message: 'Server error creating task' });
  }
};

// @desc  Update a task
// @route PUT /api/tasks/:id
const updateTask = async (req, res) => {
  try {
    const { topic, title, description, subjectId, scheduledTime, duration, completed, deadline, dueDate, priority, status } = req.body;
    
    // Validate ObjectId format
    if (!req.params.id.match(/^[0-9a-fA-F]{24}$/)) {
      return res.status(400).json({ message: 'Invalid task ID format' });
    }
    
    // Handle both frontend (title) and backend (topic) field names
    const taskTopic = topic || title;
    // Handle both frontend (dueDate) and backend (deadline) field names
    const taskDeadline = deadline || dueDate;
    
    // Verify subject ownership if subjectId is provided
    if (subjectId) {
      const subject = await Subject.findOne({ _id: subjectId, userId: req.user._id });
      if (!subject) {
        return res.status(403).json({ message: 'Access denied: Subject not found or does not belong to user' });
      }
    }
    
    const updateData = {};
    if (taskTopic !== undefined) updateData.topic = taskTopic;
    if (description !== undefined) updateData.description = description;
    if (subjectId !== undefined) updateData.subjectId = subjectId;
    if (scheduledTime !== undefined) updateData.scheduledTime = scheduledTime;
    if (duration !== undefined) updateData.duration = duration;
    if (completed !== undefined) updateData.completed = completed;
    if (taskDeadline !== undefined) updateData.deadline = taskDeadline;
    if (priority !== undefined) updateData.priority = priority;
    if (status !== undefined) updateData.status = status;
    
    const task = await Task.findOneAndUpdate(
      { _id: req.params.id, userId: req.user._id },
      { $set: updateData },
      { new: true, runValidators: true }
    );
    if (!task) return res.status(404).json({ message: 'Task not found' });
    res.json(task);
  } catch (error) {
    res.status(500).json({ message: 'Server error updating task' });
  }
};

// @desc  Delete a task
// @route DELETE /api/tasks/:id
const deleteTask = async (req, res) => {
  try {
    // Validate ObjectId format
    if (!req.params.id.match(/^[0-9a-fA-F]{24}$/)) {
      return res.status(400).json({ message: 'Invalid task ID format' });
    }
    
    const task = await Task.findOneAndDelete({ _id: req.params.id, userId: req.user._id });
    if (!task) return res.status(404).json({ message: 'Task not found' });
    res.json({ message: 'Task deleted' });
  } catch (error) {
    res.status(500).json({ message: 'Server error deleting task' });
  }
};

// @desc  Mark task as complete / incomplete
// @route PATCH /api/tasks/:id/complete
const completeTask = async (req, res) => {
  try {
    // Validate ObjectId format
    if (!req.params.id.match(/^[0-9a-fA-F]{24}$/)) {
      return res.status(400).json({ message: 'Invalid task ID format' });
    }
    
    const task = await Task.findOne({ _id: req.params.id, userId: req.user._id });
    if (!task) return res.status(404).json({ message: 'Task not found' });

    task.completed = !task.completed;
    task.status = task.completed ? 'completed' : 'pending';
    await task.save();
    res.json(task);
  } catch (error) {
    res.status(500).json({ message: 'Server error toggling task completion' });
  }
};

module.exports = { getTasks, getTask, createTask, updateTask, deleteTask, completeTask };
